### ISSUE TITLE
Kodi freezing  when tuner is being taken over for recording priority.

### ISSUE THREAD

**Issue by aklinbail** [janbar/pvr.mythtv#41]
Hi 
If there is a conflict, and recording is set to priority, Kodi is freezing when the tuner is taken over for a scheduled recording, instead of backing out to the menu, the system freezes.

**Comment by janbar** [comment]
What is the version of your MythTV backend ?

**Comment by janbar** [comment]
When priority is configured for scheduled recording, then the addon stop the live when receiving the alert message from the backend. Depending of kodi behavior (and the version of kodi maybe) it could freeze. Also you should be able to press "Stop" and return to the main screen. What is your version of Kodi ?

**Comment by ghost** [comment]
Currently using MythTV v0.28, Kodi 17.4, MythTV PVR Client v4.15.3, Ubuntu v16.04. HDHomeRun Tuners.

This issue persists. Furthermore, the scheduled recording often, if not always, doesn't start recording even though the backend reports that it is recording. So it creates a bit of a mess. I'm guessing it's a timing issue where the live stream doesn't get stopped in time for the scheduled recording to start. I'm not sure what you can do about it if you can't control the timing of the backend alert message. Perhaps there's another way to determine a conflict?

**Comment by janbar** [comment]
Seems it is a backend issue. I know there is a delay before recording starts when backend send the event.
Have you planned to upgrade to Mythtv 29 ? It runs with the addon since kodi krypton, and it could resolve the issue.

**Comment by janbar** [comment]
Checking the source code I see I placed lot of logs when processing this backend event including the delay of the backend. Can you catch the kodi log and upload it to my email account please ?

**Comment by andrewgreenwood** [comment]
I'm pretty sure I am experiencing the same issue, which mostly happens if I have a scheduled recording coming up after a program I am currently watching on the same channel. Every time this happens, live TV stops and a message is displayed to tell me that it has stopped because of a recording. Kodi becomes completely unresponsive at this point. It is very strange especially as I have a quad-tuner card and only record a small number of programs so it is rare to be viewing/recording more than maybe 2 things at a time.

Using SSH, I am able to connect to the system running Kodi (a Raspberry Pi running LibreELEC) during this time. Shortly after, Kodi restarts itself and a crash log file is created.

Strangely, in all cases I am seeing 4x ASK_RECORDING events being reported as the last thing in the Kodi MythTV add-on log, all for the same show. Each is shown with a different value after "rec=" (which I understand to be the card ID). So it looks like PVRClientMythTV::HandleAskRecording is being called multiple times (probably receiving multiple ASK_RECORDING messages from the backend in PVRClientMythTV::HandleBackendMessage ?)

Often there are errors in TransferRequestBlock reported at the same time, or immediately after (e.g. "recv data error (-1)" or "invalid response for request block (-1)".

I have the add-on "Conflict handling" option set to "Prefer live TV when recording has later slot", if this is useful information.

Backend: MythTV 0.28 on Debian Linux 8 (Jessie)
Frontend: LibreELEC 8.2.0.1 (Kodi 17.5 with MythTV PVR Client 5.0.9.1) on Raspberry Pi 3
Tuner: TBS6205 (quad TV tuner PCI Express card)

I can send you some log files if this helps.

**Comment by janbar** [comment]
Thanks @andrewgreenwood. Yes the crash log file will help. Could you send it to pastebin ? And then post the link here ?

**Comment by andrewgreenwood** [comment]
Hopefully this will help: https://pastebin.com/eJpjtYSQ

**Comment by andrewgreenwood** [comment]
I have found a way to reproduce this on-demand, though the symptom varies: In all cases it stops live TV, and sometimes it will also cause Kodi to either freeze or SIGSEGV.

The most reliable and repeatable way is to have 2 systems running Kodi (in my case I have set up a virtual machine with sources pulled from the Kodi repository and your own, and have compiled and run it on that VM). I'm running Krypton for both.

An important point I have just realised: MythTV backend may need to be configured with a tuner that has "Max recordings" set to a value greater than 1 for this problem to happen. Mine is set to 4. Because of multiplexing, there may be multiple TV shows being recorded by a single tuner. This may be a significant reason why this happens (if you have 1 recording per tuner, you probably won't get an ASK_RECORDING message for the same tuner, but if you have 4 recordings per tuner, you'll get ASK_RECORDINGs for 1,2,3,4 or 5,6,7,8 etc.).

Specific setup options I am using:
MythTV Addon - "Conflict handling": "Prefer live TV when recording has later slot"
PVR/Live TV Settings - Guide: "Default select action": "Show Information"
PVR/Live TV Settings - Playback: "Start playback minimized": Off

To reproduce the problem:
On the system you want the problem to happen on, start Kodi, go to the TV **channel listing** and start watching a channel (make a note of which channel).

On a second system, start Kodi, go to the **TV guide** and find the channel that you chose earlier.
Select the program that is currently being shown on that channel so that it displays the information about the program.
Now choose "Record" at the bottom of the screen.

Kodi on the first system will stop the live TV streaming at this point. It may freeze or SIGSEGV.

In my case, the MythTV backend status webpage originally showed that "encoder 1" was busy with the live TV. The Kodi log showed three ASK_RECORDING messages - one for card 4, then 3, then 1. After this, Kodi logged that a QueueNotification for the "Stopping Live TV" message happened.

When I checked MythTV's status webpage again, it showed that "encoder 1" was idle, and "encoder 2" was recording.

This problem only seems to happen if the recording is triggered by another system, or by a timer event (both of which cause ASK_RECORDING events). If you choose to record the current program you're watching on the same Kodi system (either from the controls on the screen or by going to the TV guide), it's fine.

The "cardid" sent for ASK_RECORDING seems to be the "encoder" number (as shown on MythTV's web frontend), and I always get 4 of these events each time (e.g. for 1234, or 5678).

Reading about this event it looks like some kind of tuner priority thing? If I switch TV channels on Kodi system 1, then 2, then 1, then 2 again, the MythTV backend seems to choose encoders 1, 5, 9 and 13 for the live TV even if the other encoders are idle. So to me it almost looks like the backend is simply offering e.g. "encoders" 1,2,3 and 4 and letting the frontend decide which one to use.

(Sorry for the really long comment, I'm just trying to put as much information as I think will be useful).

EDIT: This may actually be an issue with MythTV itself. Looking online I can see a suggested solution of setting up MythTV to set the live TV order to be the opposite of the scheduled recordings order. I think MythTV backend should probably just NOT be sending an ASK_RECORDING message for an "encoder" that is busy if there are others that can be used. Still, Kodi shouldn't coredump when this does happen though...

**Comment by janbar** [comment]
I setted my backend for live tv priority in the reverse order of recording.
What else, I had a look in the pasted log and the crash didn't occur in addon or player, but seems in the http server of kodi. Probably the json rpc. You could try to disable it in the kody settings.

**Comment by janbar** [comment]
Also you could open a track ticket in kodi bug with the crash log. It can help to fix the bug.

**Comment by ghost** [comment]
MythTV v0.28, Kodi 17.6, MythTV PVR Client v4.15.3, Ubuntu v16.04. HDHomeRun Prime Tuners.

Crash just happened again. Backend remained in tact w/o issue as recordings proceeded. Addon conflict setting is Prefer live TV when later time slot available. HTTP web server is/was disabled. Tried to post full log @pastebin but it`s too big. Can't find your email. Below is the last section of the log when live TV started up until recordings were to start and Kodi cashed.


13:52:09.487 T:140022114092800  NOTICE: PVRManager - PerformChannelSwitch - switched to channel 'MTV Hits (U.S.)'
13:52:09.487 T:140022114092800  NOTICE: Creating Demuxer
13:52:09.507 T:140023710082816 WARNING: CPVRRecording::CPVRRecording - unable to determine channel type. Defaulting to TV.
13:52:09.511 T:140022114092800 WARNING: Previous line repeats 20 times.
13:52:09.511 T:140022114092800  NOTICE: Opening stream: 0 source: 256
13:52:09.511 T:140022114092800  NOTICE: Creating video codec with codec id: 2
13:52:09.511 T:140022114092800  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: MPEG-2 video
13:52:09.511 T:140022114092800  NOTICE: Opening stream: 1 source: 256
13:52:09.511 T:140022114092800  NOTICE: Closing stream player 3
13:52:09.518 T:140022114092800  NOTICE: Opening stream: 0 source: 256
13:52:09.518 T:140022114092800  NOTICE: Creating video codec with codec id: 2
13:52:09.518 T:140022114092800  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: MPEG-2 video
13:52:09.518 T:140022114092800  NOTICE: Opening stream: 1 source: 256
13:52:09.587 T:140025989212544  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
13:52:09.596 T:140025989212544  NOTICE: GL: NPOT texture support detected
13:52:09.596 T:140025989212544  NOTICE: GL: Using GL_ARB_pixel_buffer_object
13:52:09.596 T:140025989212544  NOTICE: Using GL_TEXTURE_2D
13:52:09.599 T:140025989212544  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
13:52:09.605 T:140025989212544  NOTICE: GL: NPOT texture support detected
13:52:09.605 T:140025989212544  NOTICE: GL: Using GL_ARB_pixel_buffer_object
13:52:10.146 T:140022173062912 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
13:52:10.692 T:140023710082816 WARNING: Previous line repeats 1 times.
13:52:10.692 T:140023710082816 WARNING: CPVRRecording::CPVRRecording - unable to determine channel type. Defaulting to TV.
13:52:11.267 T:140022173062912 WARNING: Previous line repeats 20 times.
13:52:11.267 T:140022173062912  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 33366
13:52:12.567 T:140022114092800  NOTICE: Opening stream: 0 source: 256
13:52:12.567 T:140022114092800  NOTICE: Opening stream: 1 source: 256
13:52:12.567 T:140022114092800  NOTICE: Opening stream: 0 source: 1280
13:57:01.142 T:140023374063360  NOTICE: plugin.audio.spotify --> Logged in to Spotify - Username: ???
13:57:26.697 T:140022130878208   ERROR: ADDON: extension '' is not currently supported for service addon
13:58:35.762 T:140023710082816   ERROR: Previous line repeats 4 times.
13:58:35.762 T:140023710082816 WARNING: CPVRRecording::CPVRRecording - unable to determine channel type. Defaulting to TV.
13:59:30.530 T:140022954051328 WARNING: Previous line repeats 20 times.
13:59:30.530 T:140022954051328  NOTICE: AddOnLog: MythTV PVR Client: HandleAskRecording: Event ASK_RECORDING: rec=11 timeuntil=28 hasrec=0 haslater=0
13:59:30.530 T:140022954051328  NOTICE: AddOnLog: MythTV PVR Client: HandleAskRecording: Event ASK_RECORDING: title=The Talk
13:59:30.539 T:140022210602752   ERROR: AddOnLog: MythTV PVR Client: (CPPMyth)WSResponse: bad request (404)
13:59:30.539 T:140022210602752   ERROR: AddOnLog: MythTV PVR Client: (CPPMyth)GetPreviewImage1_32: invalid response
13:59:30.540 T:140022210602752   ERROR: AddOnLog: MythTV PVR Client: Process: Failed to read file: type: 1, local: /home/user/.kodi/userdata/addon_data/pvr.mythtv/cache/thumbnail/1853_1523555516_c72
13:59:30.635 T:140022114092800   ERROR: AddOnLog: MythTV PVR Client: (CPPMyth)TransferRequestBlockFeedback75: invalid response for request block (-1)
13:59:30.809 T:140022114092800   ERROR: AddOnLog: MythTV PVR Client: ReadLiveStream: Failed to read liveStream. Errorcode: -1!
13:59:30.810 T:140022114092800   ERROR: Previous line repeats 7 times.
13:59:30.810 T:140022114092800  NOTICE: VideoPlayer: next stream, wait for old streams to be finished
13:59:30.810 T:140022114092800  NOTICE: Closing stream player 1
13:59:30.810 T:140022114092800  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
13:59:31.853 T:140023710082816 WARNING: CPVRRecording::CPVRRecording - unable to determine channel type. Defaulting to TV.
13:59:32.076 T:140022114092800 WARNING: Previous line repeats 20 times.
13:59:32.076 T:140022114092800  NOTICE: Waiting for audio thread to exit
13:59:32.076 T:140022122485504   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
13:59:32.076 T:140022122485504  NOTICE: thread end: CVideoPlayerAudio::OnExit()
13:59:32.076 T:140022114092800  NOTICE: Closing audio device
13:59:32.519 T:140022114092800  NOTICE: Deleting audio codec
13:59:32.519 T:140022114092800  NOTICE: Closing stream player 2
13:59:32.519 T:140022114092800  NOTICE: CDVDMessageQueue(video)::WaitUntilEmpty
13:59:33.010 T:140025387804416  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
13:59:33.114 T:140022114092800  NOTICE: waiting for video thread to exit
13:59:33.114 T:140022173062912   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
13:59:33.114 T:140022173062912  NOTICE: thread end: video_thread
13:59:33.114 T:140022114092800  NOTICE: deleting video codec
13:59:33.115 T:140022114092800  NOTICE: CVideoPlayer::OnExit()
13:59:33.115 T:140022114092800  NOTICE: VideoPlayer: eof, waiting for queues to empty


############### END LOG FILE ################

############ END Kodi CRASH LOG #############

**Comment by janbar** [comment]
@jsnj , I need the beginning (the first part) of the crash log. The part "log file" can't help here. I just seen kodi player is ending the playback then the crash occurred.

**Comment by ghost** [comment]
I've attached it.

[kodi_crashlog-20180412_135948.log](https://github.com/janbar/pvr.mythtv/files/1911965/kodi_crashlog-20180412_135948.log)

**Comment by janbar** [comment]
Thanks to report the issue. The crash isn't related directly with the addon. It seems you had an error during memory allocation in a Kodi process calling CSaveFileStateJob. I don't know about that. You should open a track ticket in kodi and someone knowing the usage of this process could resolve the issue.

    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  _int_malloc (av=av@entry=0x7f59f8000020, bytes=bytes@entry=22) at malloc.c:3416
    #1  0x00007f5a50145184 in __GI___libc_malloc (bytes=22) at malloc.c:2913
    #2  0x00007f5a5072ee78 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #3  0x0000000000cb412a in CSaveFileStateJob::DoWork() ()
    #4  0x0000000000c78dc9 in CJobWorker::Process() ()
    #5  0x0000000000d0cf35 in CThread::Action() ()
    #6  0x0000000000d0d18f in CThread::staticThread(void*) ()
    #7  0x00007f5a5727c6ba in start_thread (arg=0x7f59715f2700) at pthread_create.c:333
    #8  0x00007f5a501c841d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by janbar** [comment]
Hi. The log show the same issue already reported here. It isn't related to the addon. The crash occurred in Kodi main. You should report this bug in the bug tracker of kodi.

**Comment by tkleinhenz** [comment]
JASON I NEED TO SPEAK WITH YOU SHOST  PLEASE JASON JEFFERY
